import { Listing, Dealer } from '@/types';

export const mockListings: Listing[] = [
  {
    id: '1',
    userId: 'user1',
    title: 'BMW 520d xDrive M-Paket',
    make: 'BMW',
    model: '520d xDrive',
    year: 2019,
    mileage: 98000,
    fuel: 'dizel',
    transmission: 'automatski',
    body: 'limuzina',
    color: 'Crna',
    power: 140,
    engineSize: 1995,
    price: 52000,
    currency: 'KM',
    negotiable: false,
    priceIncludesVAT: false,
    tradeAllowed: false,
    description: 'BMW 520d xDrive u odličnom stanju. Redovno servisiran kod ovlaštenog servisera. M-Paket, full LED, panorama krov, koža, navigacija, grijanje sjedišta. Četiri nove gume. Registrovan do 12/2026.',
    equipment: ['LED svjetla', 'Navigacija', 'Kožna sjedišta', 'Panorama krov', 'Grijanje sjedišta', 'Automatska klima', 'M paket', 'Tempomat', 'Senzori za parkiranje', 'Kamera za vožnju unazad', 'Apple CarPlay', 'Keyless entry'],
    photos: ['/placeholder-car-1.jpg'],
    city: 'Sarajevo',
    region: 'Sarajevski kanton',
    status: 'active',
    views: 1247,
    favorites: 43,
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-10'),
    registrationUntil: '12/2026',
    doors: 4,
    seats: 5,
    driveType: 'sva-cetiri',
    vin: 'WBAJC51080B123456',
    countryOfOrigin: 'Njemačka',
    previousOwners: 2,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    firstOwner: false,
    garageKept: true,
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'Admir H.',
    sellerPhone: '+387 61 234 567',
  },
  {
    id: '2',
    userId: 'user2',
    title: 'Volkswagen Golf 8 2.0 TDI DSG',
    make: 'Volkswagen',
    model: 'Golf 8 TDI',
    year: 2021,
    mileage: 45000,
    fuel: 'dizel',
    transmission: 'automatski',
    body: 'hatchback',
    color: 'Siva',
    power: 110,
    engineSize: 1968,
    price: 38500,
    currency: 'KM',
    negotiable: true,
    priceIncludesVAT: false,
    tradeAllowed: false,
    description: 'Golf 8 TDI DSG, prvi vlasnik, kupljen nov u BiH. Servisna knjiga, bez ulaganja. Digital cockpit, LED Matrix, adaptivni tempomat.',
    equipment: ['LED svjetla', 'Navigacija', 'Automatska klima', 'Tempomat', 'Senzori za parkiranje', 'Apple CarPlay', 'Android Auto', 'Bluetooth', 'Start/Stop sistem', 'ESP', 'ABS'],
    photos: ['/placeholder-car-2.jpg'],
    city: 'Banja Luka',
    region: 'Republika Srpska',
    status: 'active',
    views: 856,
    favorites: 31,
    createdAt: new Date('2026-03-08'),
    updatedAt: new Date('2026-03-08'),
    registrationUntil: '06/2026',
    doors: 4,
    seats: 5,
    driveType: 'prednji',
    countryOfOrigin: 'Bosna i Hercegovina',
    previousOwners: 1,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    firstOwner: true,
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'Dragan M.',
    sellerPhone: '+387 65 123 456',
  },
  {
    id: '3',
    userId: 'dealer1',
    title: 'Mercedes-Benz C220d AMG Line',
    make: 'Mercedes-Benz',
    model: 'C220d AMG',
    year: 2020,
    mileage: 67000,
    fuel: 'dizel',
    transmission: 'automatski',
    body: 'limuzina',
    color: 'Bijela',
    power: 143,
    engineSize: 1950,
    price: 58900,
    currency: 'KM',
    negotiable: false,
    priceIncludesVAT: true,
    tradeAllowed: true,
    description: 'Mercedes C220d AMG Line paket. Burmester zvučnici, ambijentalno osvjetljenje, multibeam LED, 360 kamera. Bez oštećenja, kao nov.',
    equipment: ['AMG paket', 'LED svjetla', 'Navigacija', 'Kožna sjedišta', 'Grijanje sjedišta', 'Automatska klima', 'Premium zvučnici', 'Kamera za vožnju unazad', 'Blind spot monitor', 'Keyless entry', 'Električna sjedišta', 'Panorama krov'],
    photos: ['/placeholder-car-3.jpg'],
    city: 'Mostar',
    region: 'Hercegovačko-neretvanski kanton',
    status: 'active',
    views: 2103,
    favorites: 87,
    createdAt: new Date('2026-03-05'),
    updatedAt: new Date('2026-03-05'),
    registrationUntil: '09/2026',
    doors: 4,
    seats: 5,
    driveType: 'zadnji',
    vin: 'WDD2050221A654321',
    countryOfOrigin: 'Njemačka',
    previousOwners: 1,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    garageKept: true,
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'AutoHaus Premium Sarajevo',
    sellerPhone: '+387 33 123 456',
  },
  {
    id: '4',
    userId: 'user3',
    title: 'Audi A4 2.0 TDI S-Tronic Avant',
    make: 'Audi',
    model: 'A4 Avant',
    year: 2018,
    mileage: 125000,
    fuel: 'dizel',
    transmission: 'automatski',
    body: 'karavan',
    color: 'Plava',
    power: 110,
    engineSize: 1968,
    price: 32000,
    currency: 'KM',
    negotiable: true,
    tradeAllowed: true,
    description: 'Audi A4 Avant u odličnom stanju. S-Tronic mjenjač, virtual cockpit, MMI navigacija, LED svjetla. Uredno servisiran.',
    equipment: ['S-Line', 'LED svjetla', 'Navigacija', 'Automatska klima', 'Tempomat', 'Senzori za parkiranje', 'Bluetooth', 'USB', 'ESP', 'ABS', 'Alu felge', 'Krovni nosači'],
    photos: ['/placeholder-car-4.jpg'],
    city: 'Tuzla',
    region: 'Tuzlanski kanton',
    status: 'active',
    views: 634,
    favorites: 22,
    createdAt: new Date('2026-03-12'),
    updatedAt: new Date('2026-03-12'),
    registrationUntil: '03/2026',
    doors: 4,
    seats: 5,
    driveType: 'prednji',
    countryOfOrigin: 'Austrija',
    previousOwners: 2,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'Emir K.',
    sellerPhone: '+387 62 987 654',
  },
  {
    id: '5',
    userId: 'dealer2',
    title: 'Toyota RAV4 2.5 Hybrid AWD',
    make: 'Toyota',
    model: 'RAV4 Hybrid',
    year: 2022,
    mileage: 28000,
    fuel: 'hibrid',
    transmission: 'automatski',
    body: 'SUV',
    color: 'Srebrna',
    power: 160,
    engineSize: 2487,
    price: 72000,
    currency: 'KM',
    negotiable: false,
    priceIncludesVAT: true,
    tradeAllowed: true,
    description: 'Toyota RAV4 Hybrid AWD-i. Premium oprema, JBL zvučnici, head-up display, adaptivni tempomat, panorama krov. Garancija do 2027.',
    equipment: ['LED svjetla', 'Navigacija', 'Automatska klima', 'Tempomat', 'Senzori za parkiranje', 'Kamera za vožnju unazad', 'Premium zvučnici', 'Apple CarPlay', 'Android Auto', 'Panorama krov', 'Grijanje sjedišta', 'Keyless entry'],
    photos: ['/placeholder-car-5.jpg'],
    city: 'Zenica',
    region: 'Zeničko-dobojski kanton',
    status: 'active',
    views: 1890,
    favorites: 65,
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-01'),
    registrationUntil: '01/2027',
    doors: 4,
    seats: 5,
    driveType: 'sva-cetiri',
    countryOfOrigin: 'Bosna i Hercegovina',
    previousOwners: 1,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    firstOwner: true,
    garageKept: true,
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'Euro Auto Centar Mostar',
    sellerPhone: '+387 36 555 789',
  },
  {
    id: '6',
    userId: 'user4',
    title: 'Škoda Octavia 1.6 TDI Combi',
    make: 'Škoda',
    model: 'Octavia Combi',
    year: 2017,
    mileage: 178000,
    fuel: 'dizel',
    transmission: 'manuelni',
    body: 'karavan',
    color: 'Smeđa',
    power: 85,
    engineSize: 1598,
    price: 18500,
    currency: 'KM',
    negotiable: true,
    tradeAllowed: false,
    description: 'Škoda Octavia Combi, ekonomično i pouzdano vozilo. Servisirana na vrijeme, klima, parking senzori, tempomat.',
    equipment: ['Klima', 'Tempomat', 'Senzori za parkiranje', 'Bluetooth', 'ESP', 'ABS', 'Električni prozori', 'Centralno zaključavanje'],
    photos: ['/placeholder-car-6.jpg'],
    city: 'Prijedor',
    region: 'Republika Srpska',
    status: 'active',
    views: 445,
    favorites: 12,
    createdAt: new Date('2026-03-13'),
    updatedAt: new Date('2026-03-13'),
    registrationUntil: '08/2026',
    doors: 4,
    seats: 5,
    driveType: 'prednji',
    countryOfOrigin: 'Slovenija',
    previousOwners: 3,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    sellerName: 'Mladen S.',
    sellerPhone: '+387 66 111 222',
  },
  {
    id: '7',
    userId: 'dealer1',
    title: 'Peugeot 3008 1.5 BlueHDi GT Line',
    make: 'Peugeot',
    model: '3008 GT Line',
    year: 2020,
    mileage: 82000,
    fuel: 'dizel',
    transmission: 'automatski',
    body: 'SUV',
    color: 'Crna',
    power: 96,
    engineSize: 1499,
    price: 39900,
    currency: 'KM',
    negotiable: false,
    priceIncludesVAT: true,
    tradeAllowed: true,
    description: 'Peugeot 3008 GT Line sa i-Cockpit instrumentima. Full LED, panorama krov, el. hauba, Night Vision. Top stanje.',
    equipment: ['LED svjetla', 'Navigacija', 'Panorama krov', 'Automatska klima', 'Tempomat', 'Senzori za parkiranje', 'Kamera za vožnju unazad', 'Apple CarPlay', 'Android Auto', 'Touchscreen', 'Alu felge'],
    photos: ['/placeholder-car-7.jpg'],
    city: 'Sarajevo',
    region: 'Sarajevski kanton',
    status: 'active',
    views: 723,
    favorites: 28,
    createdAt: new Date('2026-03-07'),
    updatedAt: new Date('2026-03-07'),
    registrationUntil: '11/2026',
    doors: 4,
    seats: 5,
    driveType: 'prednji',
    countryOfOrigin: 'Francuska',
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'AutoHaus Premium Sarajevo',
    sellerPhone: '+387 33 123 456',
  },
  {
    id: '8',
    userId: 'user5',
    title: 'Opel Astra 1.4 Turbo',
    make: 'Opel',
    model: 'Astra K',
    year: 2019,
    mileage: 93000,
    fuel: 'benzin',
    transmission: 'manuelni',
    body: 'hatchback',
    color: 'Crvena',
    power: 110,
    engineSize: 1399,
    price: 21000,
    currency: 'KM',
    negotiable: true,
    tradeAllowed: false,
    description: 'Opel Astra 1.4 Turbo, odličan za grad i duge relacije. Ekonomičan motor, puno opreme za klasu.',
    equipment: ['LED svjetla', 'Klima', 'Tempomat', 'Bluetooth', 'USB', 'ESP', 'ABS', 'Alu felge', 'Električni prozori', 'Centralno zaključavanje', 'Isofix'],
    photos: ['/placeholder-car-8.jpg'],
    city: 'Bijeljina',
    region: 'Republika Srpska',
    status: 'active',
    views: 312,
    favorites: 9,
    createdAt: new Date('2026-03-14'),
    updatedAt: new Date('2026-03-14'),
    registrationUntil: '04/2026',
    doors: 4,
    seats: 5,
    driveType: 'prednji',
    countryOfOrigin: 'Njemačka',
    previousOwners: 2,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    sellerName: 'Amir B.',
    sellerPhone: '+387 61 555 666',
  },
  {
    id: '9',
    userId: 'user6',
    title: 'Volkswagen Passat 2.0 TDI Comfortline',
    make: 'Volkswagen',
    model: 'Passat B8',
    year: 2016,
    mileage: 210000,
    fuel: 'dizel',
    transmission: 'manuelni',
    body: 'karavan',
    color: 'Srebrna',
    power: 110,
    engineSize: 1968,
    price: 19500,
    currency: 'KM',
    negotiable: true,
    tradeAllowed: true,
    description: 'Passat B8 Comfortline, redovno servisiran, veliki servis upravo urađen. Odličan porodični auto. Navigacija, parking senzori naprijed i nazad.',
    equipment: ['Navigacija', 'Automatska klima', 'Tempomat', 'Senzori za parkiranje', 'Bluetooth', 'ESP', 'ABS', 'Alu felge', 'Električni prozori', 'Krovni nosači'],
    photos: ['/placeholder-car-9.jpg'],
    city: 'Travnik',
    region: 'Srednjobosanski kanton',
    status: 'active',
    views: 567,
    favorites: 18,
    createdAt: new Date('2026-03-11'),
    updatedAt: new Date('2026-03-11'),
    registrationUntil: '10/2026',
    doors: 4,
    seats: 5,
    driveType: 'prednji',
    countryOfOrigin: 'Njemačka',
    previousOwners: 3,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    serviceBook: true,
    sellerName: 'Haris T.',
    sellerPhone: '+387 63 444 555',
  },
  {
    id: '10',
    userId: 'dealer3',
    title: 'Audi A6 3.0 TDI Quattro S-Line',
    make: 'Audi',
    model: 'A6 Quattro',
    year: 2019,
    mileage: 135000,
    fuel: 'dizel',
    transmission: 'automatski',
    body: 'limuzina',
    color: 'Crna',
    power: 170,
    engineSize: 2967,
    price: 55000,
    currency: 'KM',
    negotiable: false,
    priceIncludesVAT: true,
    tradeAllowed: true,
    description: 'Audi A6 3.0 TDI Quattro sa S-Line paketom. Matrix LED, virtual cockpit, Bang & Olufsen zvuk, adaptivni tempomat. Perfektno stanje.',
    equipment: ['S-Line', 'LED svjetla', 'Navigacija', 'Kožna sjedišta', 'Grijanje sjedišta', 'Automatska klima', 'Premium zvučnici', 'Tempomat', 'Senzori za parkiranje', 'Kamera za vožnju unazad', 'Blind spot monitor', 'Keyless entry', 'Panorama krov', 'Alu felge'],
    photos: ['/placeholder-car-10.jpg'],
    city: 'Banja Luka',
    region: 'Republika Srpska',
    status: 'active',
    views: 1456,
    favorites: 52,
    createdAt: new Date('2026-03-09'),
    updatedAt: new Date('2026-03-09'),
    registrationUntil: '07/2026',
    doors: 4,
    seats: 5,
    driveType: 'sva-cetiri',
    vin: 'WAUZZZ4G9KN012345',
    countryOfOrigin: 'Njemačka',
    previousOwners: 2,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    garageKept: true,
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'Autoland Banja Luka',
    sellerPhone: '+387 51 222 333',
  },
  {
    id: '11',
    userId: 'user7',
    title: 'Renault Megane 1.5 dCi Zen',
    make: 'Renault',
    model: 'Megane IV',
    year: 2018,
    mileage: 142000,
    fuel: 'dizel',
    transmission: 'manuelni',
    body: 'hatchback',
    color: 'Plava',
    power: 81,
    engineSize: 1461,
    price: 14900,
    currency: 'KM',
    negotiable: true,
    tradeAllowed: false,
    description: 'Renault Megane 1.5 dCi, veoma ekonomično vozilo. Idealan za dnevne vožnje. Klima, navigacija, tempomat. Registrovan.',
    equipment: ['Navigacija', 'Klima', 'Tempomat', 'Bluetooth', 'USB', 'ESP', 'ABS', 'Električni prozori', 'Centralno zaključavanje'],
    photos: ['/placeholder-car-11.jpg'],
    city: 'Živinice',
    region: 'Tuzlanski kanton',
    status: 'active',
    views: 234,
    favorites: 7,
    createdAt: new Date('2026-03-14'),
    updatedAt: new Date('2026-03-14'),
    registrationUntil: '05/2026',
    doors: 4,
    seats: 5,
    driveType: 'prednji',
    countryOfOrigin: 'Francuska',
    previousOwners: 2,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    sellerName: 'Jasmin A.',
    sellerPhone: '+387 62 333 444',
  },
  {
    id: '12',
    userId: 'user8',
    title: 'BMW 320d M-Sport G20',
    make: 'BMW',
    model: '320d G20',
    year: 2020,
    mileage: 78000,
    fuel: 'dizel',
    transmission: 'automatski',
    body: 'limuzina',
    color: 'Siva',
    power: 140,
    engineSize: 1995,
    price: 48500,
    currency: 'KM',
    negotiable: false,
    tradeAllowed: false,
    description: 'BMW 320d M-Sport paket, G20 generacija. Live Cockpit Professional, harman/kardon zvuk, M kočnice. Bez ikakvog oštećenja.',
    equipment: ['M paket', 'LED svjetla', 'Navigacija', 'Kožna sjedišta', 'Grijanje sjedišta', 'Automatska klima', 'Premium zvučnici', 'Tempomat', 'Senzori za parkiranje', 'Kamera za vožnju unazad', 'Apple CarPlay', 'Keyless entry', 'Alu felge'],
    photos: ['/placeholder-car-12.jpg'],
    city: 'Sarajevo',
    region: 'Sarajevski kanton',
    status: 'active',
    views: 987,
    favorites: 41,
    createdAt: new Date('2026-03-06'),
    updatedAt: new Date('2026-03-06'),
    registrationUntil: '02/2027',
    doors: 4,
    seats: 5,
    driveType: 'zadnji',
    vin: 'WBA5R11080A789012',
    countryOfOrigin: 'Njemačka',
    previousOwners: 1,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    garageKept: true,
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'Kenan P.',
    sellerPhone: '+387 61 888 999',
  },
  {
    id: '13',
    userId: 'dealer2',
    title: 'Mercedes-Benz E220d Avantgarde',
    make: 'Mercedes-Benz',
    model: 'E220d W213',
    year: 2017,
    mileage: 165000,
    fuel: 'dizel',
    transmission: 'automatski',
    body: 'limuzina',
    color: 'Crna',
    power: 143,
    engineSize: 1950,
    price: 39500,
    currency: 'KM',
    negotiable: true,
    priceIncludesVAT: true,
    tradeAllowed: true,
    description: 'Mercedes E220d Avantgarde, W213 generacija. Widescreen cockpit, Comand Online navigacija, LED Intelligent Light System. Moguća zamjena za novije SUV.',
    equipment: ['LED svjetla', 'Navigacija', 'Kožna sjedišta', 'Grijanje sjedišta', 'Automatska klima', 'Tempomat', 'Senzori za parkiranje', 'Kamera za vožnju unazad', 'Bluetooth', 'USB', 'Električna sjedišta', 'Alu felge'],
    photos: ['/placeholder-car-13.jpg'],
    city: 'Mostar',
    region: 'Hercegovačko-neretvanski kanton',
    status: 'active',
    views: 1034,
    favorites: 38,
    createdAt: new Date('2026-03-04'),
    updatedAt: new Date('2026-03-04'),
    registrationUntil: '11/2026',
    doors: 4,
    seats: 5,
    driveType: 'zadnji',
    countryOfOrigin: 'Njemačka',
    previousOwners: 2,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'Euro Auto Centar Mostar',
    sellerPhone: '+387 36 555 789',
  },
  {
    id: '14',
    userId: 'user9',
    title: 'Volkswagen Golf 7 1.6 TDI',
    make: 'Volkswagen',
    model: 'Golf 7',
    year: 2015,
    mileage: 198000,
    fuel: 'dizel',
    transmission: 'manuelni',
    body: 'hatchback',
    color: 'Bijela',
    power: 81,
    engineSize: 1598,
    price: 14500,
    currency: 'KM',
    negotiable: true,
    tradeAllowed: false,
    description: 'Golf 7 1.6 TDI, Bluemotion paket. Veoma ekonomičan, troši 4.5l/100km. Uredno servisiran, nove kočnice. Idealan prvi auto.',
    equipment: ['Klima', 'Tempomat', 'Bluetooth', 'ESP', 'ABS', 'Električni prozori', 'Centralno zaključavanje', 'Isofix', 'Start/Stop sistem'],
    photos: ['/placeholder-car-14.jpg'],
    city: 'Brčko',
    region: 'Brčko distrikt',
    status: 'active',
    views: 678,
    favorites: 25,
    createdAt: new Date('2026-03-13'),
    updatedAt: new Date('2026-03-13'),
    registrationUntil: '09/2026',
    doors: 4,
    seats: 5,
    driveType: 'prednji',
    countryOfOrigin: 'Njemačka',
    previousOwners: 3,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    sellerName: 'Nermin Z.',
    sellerPhone: '+387 66 777 888',
  },
  {
    id: '15',
    userId: 'user10',
    title: 'Fiat 500 1.2 Lounge',
    make: 'Fiat',
    model: '500 Lounge',
    year: 2018,
    mileage: 68000,
    fuel: 'benzin',
    transmission: 'manuelni',
    body: 'hatchback',
    color: 'Crvena',
    power: 51,
    engineSize: 1242,
    price: 12900,
    currency: 'KM',
    negotiable: false,
    tradeAllowed: false,
    description: 'Fiat 500 Lounge, panorama krov, klima, city mod. Savršen gradski auto. Ženske ruke, garažiran.',
    equipment: ['Panorama krov', 'Klima', 'Bluetooth', 'USB', 'ESP', 'ABS', 'Električni prozori', 'Centralno zaključavanje', 'Alu felge'],
    photos: ['/placeholder-car-15.jpg'],
    city: 'Široki Brijeg',
    region: 'Zapadnohercegovački kanton',
    status: 'active',
    views: 189,
    favorites: 14,
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
    registrationUntil: '06/2026',
    doors: 2,
    seats: 4,
    driveType: 'prednji',
    countryOfOrigin: 'Italija',
    previousOwners: 1,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    firstOwner: true,
    garageKept: true,
    sellerName: 'Ivana M.',
    sellerPhone: '+387 63 222 333',
  },
  {
    id: '16',
    userId: 'dealer3',
    title: 'Škoda Superb 2.0 TDI Style',
    make: 'Škoda',
    model: 'Superb III',
    year: 2019,
    mileage: 110000,
    fuel: 'dizel',
    transmission: 'automatski',
    body: 'karavan',
    color: 'Siva',
    power: 110,
    engineSize: 1968,
    price: 34900,
    currency: 'KM',
    negotiable: false,
    priceIncludesVAT: true,
    tradeAllowed: true,
    description: 'Škoda Superb Combi Style, najprostranije vozilo u klasi. Canton zvučnici, LED svjetla, virtual cockpit. Zamjena moguća uz doplatu.',
    equipment: ['LED svjetla', 'Navigacija', 'Automatska klima', 'Tempomat', 'Senzori za parkiranje', 'Kamera za vožnju unazad', 'Bluetooth', 'Apple CarPlay', 'Android Auto', 'Premium zvučnici', 'Alu felge', 'Krovni nosači', 'Električna sjedišta'],
    photos: ['/placeholder-car-16.jpg'],
    city: 'Banja Luka',
    region: 'Republika Srpska',
    status: 'active',
    views: 845,
    favorites: 33,
    createdAt: new Date('2026-03-02'),
    updatedAt: new Date('2026-03-02'),
    registrationUntil: '12/2026',
    doors: 4,
    seats: 5,
    driveType: 'prednji',
    vin: 'TMBGE73V5K3012345',
    countryOfOrigin: 'Češka',
    previousOwners: 1,
    damageStatus: 'bez-ostecenja',
    registrationStatus: 'registrovan',
    serviceBook: true,
    allChecksAllowed: true,
    sellerName: 'Autoland Banja Luka',
    sellerPhone: '+387 51 222 333',
  },
];

export const mockDealers: Dealer[] = [
  {
    userId: 'dealer1',
    businessName: 'AutoHaus Premium Sarajevo',
    logo: '/placeholder-dealer-logo.jpg',
    coverPhoto: '/placeholder-dealer-cover.jpg',
    description: 'Ovlašteni prodavac premium rabljenih vozila. Svako vozilo prolazi detaljnu inspekciju od 150 tačaka. Garancija na svako vozilo.',
    address: 'Zmaja od Bosne 7',
    city: 'Sarajevo',
    phone: '+387 33 123 456',
    email: 'info@autohaus-sarajevo.ba',
    website: 'https://autohaus-sarajevo.ba',
    workingHours: 'Pon-Pet: 08:00-18:00, Sub: 09:00-14:00',
    package: 'premium',
    packageExpiry: new Date('2026-12-31'),
    verified: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    userId: 'dealer2',
    businessName: 'Euro Auto Centar Mostar',
    logo: '/placeholder-dealer-logo.jpg',
    coverPhoto: '/placeholder-dealer-cover.jpg',
    description: 'Više od 15 godina iskustva u prodaji kvalitetnih rabljenih vozila. Finansiranje, zamjena, otkup.',
    address: 'Bišće polje bb',
    city: 'Mostar',
    phone: '+387 36 555 789',
    email: 'prodaja@euroauto-mostar.ba',
    workingHours: 'Pon-Pet: 08:30-17:30, Sub: 09:00-13:00',
    package: 'standard',
    packageExpiry: new Date('2026-06-30'),
    verified: true,
    rating: 4.5,
    reviewCount: 67,
  },
  {
    userId: 'dealer3',
    businessName: 'Autoland Banja Luka',
    logo: '/placeholder-dealer-logo.jpg',
    coverPhoto: '/placeholder-dealer-cover.jpg',
    description: 'Najširi izbor vozila u Krajini. Preko 100 vozila na stanju. Povoljno finansiranje i osiguranje na licu mjesta.',
    address: 'Bulevar vojvode Stepe 45',
    city: 'Banja Luka',
    phone: '+387 51 222 333',
    email: 'info@autoland-bl.ba',
    workingHours: 'Pon-Sub: 08:00-17:00',
    package: 'vip',
    packageExpiry: new Date('2026-12-31'),
    verified: true,
    rating: 4.6,
    reviewCount: 203,
  },
];
